#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 21, 2018 11:25:38 PM JST  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import traitedit_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    traitedit_support.set_Tk_var()
    top = EDCT_Explore (root)
    traitedit_support.init(root, top)
    root.mainloop()

w = None
def create_EDCT_Explore(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    traitedit_support.set_Tk_var()
    top = EDCT_Explore (w)
    traitedit_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_EDCT_Explore():
    global w
    w.destroy()
    w = None


class EDCT_Explore:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1150x589+632+401")
        top.title("EDCT Explore")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.PaneWin = ttk.Panedwindow(top, orient="horizontal")
        self.PaneWin.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.TraitPane = ttk.Labelframe(width=338, text='Traits')
        self.PaneWin.add(self.TraitPane)
        self.EditPane = ttk.Labelframe(width=455, text='Workspace')
        self.PaneWin.add(self.EditPane)
        self.TriggerPane = ttk.Labelframe(text='Triggers')
        self.PaneWin.add(self.TriggerPane)
        self.__funcid0 = self.PaneWin.bind('<Map>', self.__adjust_sash0)

        self.TraitListt = ScrolledListBox(self.TraitPane)
        self.TraitListt.place(relx=0.0, rely=0.136, relheight=1.024
                , relwidth=0.988, bordermode='ignore')
        self.TraitListt.configure(background="white")
        self.TraitListt.configure(disabledforeground="#a3a3a3")
        self.TraitListt.configure(font=font10)
        self.TraitListt.configure(foreground="black")
        self.TraitListt.configure(highlightbackground="#d9d9d9")
        self.TraitListt.configure(highlightcolor="#d9d9d9")
        self.TraitListt.configure(selectbackground="#c4c4c4")
        self.TraitListt.configure(selectforeground="black")
        self.TraitListt.configure(width=10)
        self.TraitListt.configure(listvariable=traitedit_support.TraitList)

        self.TraitButtonFrame = ttk.Frame(self.TraitPane)
        self.TraitButtonFrame.place(relx=0.0, rely=0.034, relheight=0.107
                , relwidth=0.991, bordermode='ignore')
        self.TraitButtonFrame.configure(relief=GROOVE)
        self.TraitButtonFrame.configure(borderwidth="2")
        self.TraitButtonFrame.configure(relief=GROOVE)
        self.TraitButtonFrame.configure(width=335)

        self.FindAllTrait = ttk.Button(self.TraitButtonFrame)
        self.FindAllTrait.place(relx=0.015, rely=0.0, height=26, width=68)
        self.FindAllTrait.configure(command=traitedit_support.FindAllTraits)
        self.FindAllTrait.configure(takefocus="")
        self.FindAllTrait.configure(text='''Find all''')

        self.style.map('TCheckbutton',background=
            [('selected', _bgcolor), ('active', _ana2color)])
        self.TraitCaseSensitive = ttk.Checkbutton(self.TraitButtonFrame)
        self.TraitCaseSensitive.place(relx=0.239, rely=0.079, relwidth=0.137
                , relheight=0.0, height=19)
        self.TraitCaseSensitive.configure(variable=traitedit_support.TraitCaseSens)
        self.TraitCaseSensitive.configure(takefocus="")
        self.TraitCaseSensitive.configure(text='''cC''')

        self.InvertTraitSelection = ttk.Button(self.TraitButtonFrame)
        self.InvertTraitSelection.place(relx=0.507, rely=0.0, height=26
                , width=59)
        self.InvertTraitSelection.configure(command=traitedit_support.InvertTraitSelection)
        self.InvertTraitSelection.configure(takefocus="")
        self.InvertTraitSelection.configure(text='''Invert''')

        self.HideTrait = ttk.Button(self.TraitButtonFrame)
        self.HideTrait.place(relx=0.687, rely=0.0, height=26, width=42)
        self.HideTrait.configure(command=traitedit_support.HideTrait)
        self.HideTrait.configure(takefocus="")
        self.HideTrait.configure(text='''Hide''')

        self.ReloadTraitList = ttk.Button(self.TraitButtonFrame)
        self.ReloadTraitList.place(relx=0.821, rely=0.0, height=26, width=54)
        self.ReloadTraitList.configure(command=traitedit_support.ReloadTraitList)
        self.ReloadTraitList.configure(takefocus="")
        self.ReloadTraitList.configure(text='''Reload''')

        self.TraitSearchEntry = ttk.Entry(self.TraitButtonFrame)
        self.TraitSearchEntry.place(relx=0.015, rely=0.476, relheight=0.413
                , relwidth=0.513)
        self.TraitSearchEntry.configure(textvariable=traitedit_support.traitsearched)
        self.TraitSearchEntry.configure(takefocus="")
        self.TraitSearchEntry.configure(cursor="xterm")

        self.TraitGoToPrev = ttk.Button(self.TraitButtonFrame)
        self.TraitGoToPrev.place(relx=0.537, rely=0.476, height=26, width=23)
        self.TraitGoToPrev.configure(command=traitedit_support.TraitGoToPrev)
        self.TraitGoToPrev.configure(takefocus="")
        self.TraitGoToPrev.configure(text='''<''')

        self.TraitGoToNext = ttk.Button(self.TraitButtonFrame)
        self.TraitGoToNext.place(relx=0.612, rely=0.476, height=26, width=23)
        self.TraitGoToNext.configure(command=traitedit_support.TraitGoToNext)
        self.TraitGoToNext.configure(takefocus="")
        self.TraitGoToNext.configure(text='''>''')

        self.AddTrait = ttk.Button(self.TraitButtonFrame)
        self.AddTrait.place(relx=0.687, rely=0.476, height=26, width=48)
        self.AddTrait.configure(command=traitedit_support.AddTrait)
        self.AddTrait.configure(takefocus="")
        self.AddTrait.configure(text='''Add''')

        self.DeleteTrait = ttk.Button(self.TraitButtonFrame)
        self.DeleteTrait.place(relx=0.836, rely=0.476, height=26, width=51)
        self.DeleteTrait.configure(command=traitedit_support.DeleteTrait)
        self.DeleteTrait.configure(takefocus="")
        self.DeleteTrait.configure(text='''Delete''')

        self.Viewer = ScrolledText(self.EditPane)
        self.Viewer.place(relx=0.0, rely=0.136, relheight=1.024, relwidth=1.0
                , bordermode='ignore')
        self.Viewer.configure(background="white")
        self.Viewer.configure(font=font9)
        self.Viewer.configure(foreground="black")
        self.Viewer.configure(highlightbackground="#d9d9d9")
        self.Viewer.configure(highlightcolor="black")
        self.Viewer.configure(insertbackground="black")
        self.Viewer.configure(insertborderwidth="3")
        self.Viewer.configure(selectbackground="#c4c4c4")
        self.Viewer.configure(selectforeground="black")
        self.Viewer.configure(width=10)
        self.Viewer.configure(wrap=NONE)

        self.EditButtonFrame = ttk.Frame(self.EditPane)
        self.EditButtonFrame.place(relx=0.0, rely=0.034, relheight=0.076
                , relwidth=1.0, bordermode='ignore')
        self.EditButtonFrame.configure(relief=GROOVE)
        self.EditButtonFrame.configure(borderwidth="2")
        self.EditButtonFrame.configure(relief=GROOVE)
        self.EditButtonFrame.configure(width=455)

        self.ValidEdit = ttk.Button(self.EditButtonFrame)
        self.ValidEdit.place(relx=0.022, rely=0.222, height=30, width=68)
        self.ValidEdit.configure(command=traitedit_support.ValidEdit)
        self.ValidEdit.configure(takefocus="")
        self.ValidEdit.configure(text='''Validate''')

        self.SaveEdit = ttk.Button(self.EditButtonFrame)
        self.SaveEdit.place(relx=0.176, rely=0.222, height=30, width=58)
        self.SaveEdit.configure(command=traitedit_support.SaveEdit)
        self.SaveEdit.configure(takefocus="")
        self.SaveEdit.configure(text='''Save''')

        self.ReloadEdit = ttk.Button(self.EditButtonFrame)
        self.ReloadEdit.place(relx=0.308, rely=0.222, height=30, width=78)
        self.ReloadEdit.configure(command=traitedit_support.ReloadEdit)
        self.ReloadEdit.configure(takefocus="")
        self.ReloadEdit.configure(text='''Reload''')

        self.ClearEdit = ttk.Button(self.EditButtonFrame)
        self.ClearEdit.place(relx=0.484, rely=0.222, height=30, width=78)
        self.ClearEdit.configure(command=traitedit_support.ClearEdit)
        self.ClearEdit.configure(takefocus="")
        self.ClearEdit.configure(text='''Clear''')

        self.ExportEdit = ttk.Button(self.EditButtonFrame)
        self.ExportEdit.place(relx=0.659, rely=0.222, height=30, width=68)
        self.ExportEdit.configure(command=traitedit_support.ExportEdit)
        self.ExportEdit.configure(takefocus="")
        self.ExportEdit.configure(text='''Export''')

        self.ImportEdit = ttk.Button(self.EditButtonFrame)
        self.ImportEdit.place(relx=0.813, rely=0.222, height=30, width=78)
        self.ImportEdit.configure(command=traitedit_support.ImportEdit)
        self.ImportEdit.configure(takefocus="")
        self.ImportEdit.configure(text='''Import''')

        self.TriggerListt = ScrolledListBox(self.TriggerPane)
        self.TriggerListt.place(relx=0.0, rely=0.136, relheight=1.024
                , relwidth=0.994, bordermode='ignore')
        self.TriggerListt.configure(background="white")
        self.TriggerListt.configure(disabledforeground="#a3a3a3")
        self.TriggerListt.configure(font=font10)
        self.TriggerListt.configure(foreground="black")
        self.TriggerListt.configure(highlightbackground="#d9d9d9")
        self.TriggerListt.configure(highlightcolor="#d9d9d9")
        self.TriggerListt.configure(selectbackground="#c4c4c4")
        self.TriggerListt.configure(selectforeground="black")
        self.TriggerListt.configure(width=10)
        self.TriggerListt.configure(listvariable=traitedit_support.TriggerList)

        self.TriggerButtonFrame = ttk.Frame(self.TriggerPane)
        self.TriggerButtonFrame.place(relx=0.0, rely=0.034, relheight=0.107
                , relwidth=0.965, bordermode='ignore')
        self.TriggerButtonFrame.configure(relief=GROOVE)
        self.TriggerButtonFrame.configure(borderwidth="2")
        self.TriggerButtonFrame.configure(relief=GROOVE)
        self.TriggerButtonFrame.configure(width=335)

        self.FindAllTriggers = ttk.Button(self.TriggerButtonFrame)
        self.FindAllTriggers.place(relx=0.015, rely=0.0, height=26, width=68)
        self.FindAllTriggers.configure(command=traitedit_support.FindAllTriggers)
        self.FindAllTriggers.configure(takefocus="")
        self.FindAllTriggers.configure(text='''Find all''')

        self.TriggerCaseSensitive = ttk.Checkbutton(self.TriggerButtonFrame)
        self.TriggerCaseSensitive.place(relx=0.239, rely=0.079, relwidth=0.137
                , relheight=0.0, height=19)
        self.TriggerCaseSensitive.configure(variable=traitedit_support.TriggCaseSens)
        self.TriggerCaseSensitive.configure(takefocus="")
        self.TriggerCaseSensitive.configure(text='''cC''')

        self.InvertTriggerSelection = ttk.Button(self.TriggerButtonFrame)
        self.InvertTriggerSelection.place(relx=0.507, rely=0.0, height=26
                , width=59)
        self.InvertTriggerSelection.configure(command=traitedit_support.InvertTriggerSelection)
        self.InvertTriggerSelection.configure(takefocus="")
        self.InvertTriggerSelection.configure(text='''Invert''')

        self.HideTrigger = ttk.Button(self.TriggerButtonFrame)
        self.HideTrigger.place(relx=0.687, rely=0.0, height=26, width=42)
        self.HideTrigger.configure(command=traitedit_support.HideTrigger)
        self.HideTrigger.configure(takefocus="")
        self.HideTrigger.configure(text='''Hide''')

        self.ReloadTriggerList = ttk.Button(self.TriggerButtonFrame)
        self.ReloadTriggerList.place(relx=0.836, rely=0.0, height=26, width=54)
        self.ReloadTriggerList.configure(command=traitedit_support.ReloadTriggerList)
        self.ReloadTriggerList.configure(takefocus="")
        self.ReloadTriggerList.configure(text='''Reload''')

        self.TriggerSearchEntry = ttk.Entry(self.TriggerButtonFrame)
        self.TriggerSearchEntry.place(relx=0.015, rely=0.476, relheight=0.413
                , relwidth=0.513)
        self.TriggerSearchEntry.configure(textvariable=traitedit_support.triggersearched)
        self.TriggerSearchEntry.configure(takefocus="")
        self.TriggerSearchEntry.configure(cursor="xterm")

        self.TriggGoToPrev = ttk.Button(self.TriggerButtonFrame)
        self.TriggGoToPrev.place(relx=0.537, rely=0.476, height=26, width=23)
        self.TriggGoToPrev.configure(command=traitedit_support.TriggGoToPrev)
        self.TriggGoToPrev.configure(takefocus="")
        self.TriggGoToPrev.configure(text='''<''')

        self.TriggGoToNext = ttk.Button(self.TriggerButtonFrame)
        self.TriggGoToNext.place(relx=0.612, rely=0.476, height=26, width=23)
        self.TriggGoToNext.configure(command=traitedit_support.TriggGoToNext)
        self.TriggGoToNext.configure(takefocus="")
        self.TriggGoToNext.configure(text='''>''')

        self.AddTrigger = ttk.Button(self.TriggerButtonFrame)
        self.AddTrigger.place(relx=0.687, rely=0.476, height=26, width=48)
        self.AddTrigger.configure(command=traitedit_support.AddTrigger)
        self.AddTrigger.configure(takefocus="")
        self.AddTrigger.configure(text='''Add''')

        self.DeleteTrigger = ttk.Button(self.TriggerButtonFrame)
        self.DeleteTrigger.place(relx=0.836, rely=0.476, height=26, width=51)
        self.DeleteTrigger.configure(command=traitedit_support.DeleteTrigger)
        self.DeleteTrigger.configure(takefocus="")
        self.DeleteTrigger.configure(text='''Delete''')

        self.menubar = Menu(top,font=font9,bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=traitedit_support.OpenFile,
                font=('Segoe UI',9,'normal','roman',),
                foreground="#000000",
                label="Open")
        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=traitedit_support.ReloadFile,
                font=('Segoe UI',9,'normal','roman',),
                foreground="#000000",
                label="Reload")
        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=traitedit_support.SaveFile,
                font=('DejaVu Sans',9,'normal','roman',),
                foreground="#000000",
                label="Save")
        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=traitedit_support.SaveFileAs,
                font=('Segoe UI',9,'normal','roman',),
                foreground="#000000",
                label="Save as")
        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=traitedit_support.ValidateFile,
                font=('Segoe UI',9,'normal','roman',),
                foreground="#000000",
                label="Validate")
        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=traitedit_support.FilterWin,
                font=('DejaVu Sans',9,'normal','roman',),
                foreground="#000000",
                label="Filters")
        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                compound="left",
                font=font9,
                foreground="#000000",
                label="Options")
        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=traitedit_support.Quit,
                font=('Segoe UI',9,'normal','roman',),
                foreground="#000000",
                label="Quit")




    def __adjust_sash0(self, event):
        paned = event.widget
        pos = [338, 798, ]
        i = 0
        for sash in pos:
            paned.sashpos(i, sash)
            i += 1
        paned.unbind('<map>', self.__funcid0)
        del self.__funcid0




# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = Pack.__dict__.keys() | Grid.__dict__.keys() \
                  | Place.__dict__.keys()
        else:
            methods = Pack.__dict__.keys() + Grid.__dict__.keys() \
                  + Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

class ScrolledListBox(AutoScroll, Listbox):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

if __name__ == '__main__':
    vp_start_gui()



