#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Nov 14, 2018 09:04:01 PM JST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans Mono} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font font9 \
"-family {DejaVu Sans} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m41" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1150x689+479+261
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1030
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "EDCT Explore"
    vTcl:DefineAlias "$top" "TraitGUI" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TPanedwindow -background #d9d9d9
    ttk::style configure TPanedwindow.Label -background #d9d9d9
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font TkDefaultFont
    ttk::panedwindow $top.tPa40 \
        -orient horizontal 
    vTcl:DefineAlias "$top.tPa40" "PaneWin" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa40.p1 \
        -text Traits -width 338 -height 460 
    vTcl:DefineAlias "$top.tPa40.p1" "TraitPane" vTcl:WidgetProc "TraitGUI" 1
    set site_4_0 $top.tPa40.p1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_0.scr43 \
        -background {#d9d9d9} -height 603 -highlightcolor black -width 334 
    vTcl:DefineAlias "$site_4_0.scr43" "TraitListt" vTcl:WidgetProc "TraitGUI" 1

    $site_4_0.scr43.01 configure -background white \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -listvariable TraitList
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $site_4_0.tFr40 \
        -borderwidth 2 -relief groove -width 335 -height 70 
    vTcl:DefineAlias "$site_4_0.tFr40" "TraitButtonFrame" vTcl:WidgetProc "TraitGUI" 1
    set site_5_0 $site_4_0.tFr40
    ttk::entry $site_5_0.tEn41 \
        -textvariable traitsearched -foreground {} -background {} \
        -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_5_0.tEn41" "TraitSearchEntry" vTcl:WidgetProc "TraitGUI" 1
    vTcl:copy_lock $site_5_0.tEn41
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu42 \
        -command FindAllTraits -takefocus {} -text {Find all} 
    vTcl:DefineAlias "$site_5_0.tBu42" "FindAllTrait" vTcl:WidgetProc "TraitGUI" 1
    vTcl:copy_lock $site_5_0.tBu42
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu43 \
        -takefocus {} -text < 
    vTcl:DefineAlias "$site_5_0.tBu43" "TraitGoToPrev" vTcl:WidgetProc "TraitGUI" 1
    vTcl:copy_lock $site_5_0.tBu43
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu44 \
        -takefocus {} -text > 
    vTcl:DefineAlias "$site_5_0.tBu44" "TraitGoToNext" vTcl:WidgetProc "TraitGUI" 1
    vTcl:copy_lock $site_5_0.tBu44
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu45 \
        -command AddTrait -takefocus {} -text Add 
    vTcl:DefineAlias "$site_5_0.tBu45" "AddTrait" vTcl:WidgetProc "TraitGUI" 1
    vTcl:copy_lock $site_5_0.tBu45
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu46 \
        -command HideTrait -takefocus {} -text Hide 
    vTcl:DefineAlias "$site_5_0.tBu46" "HideTrait" vTcl:WidgetProc "TraitGUI" 1
    vTcl:copy_lock $site_5_0.tBu46
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu47 \
        -command ReloadTraitList -takefocus {} -text Reload 
    vTcl:DefineAlias "$site_5_0.tBu47" "ReloadTraitList" vTcl:WidgetProc "TraitGUI" 1
    vTcl:copy_lock $site_5_0.tBu47
    place $site_5_0.tEn41 \
        -in $site_5_0 -x 5 -y 30 -width 172 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu42 \
        -in $site_5_0 -x 5 -y 2 -width 68 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_5_0.tBu43 \
        -in $site_5_0 -x 180 -y 30 -width 23 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tBu44 \
        -in $site_5_0 -x 205 -y 30 -width 23 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu45 \
        -in $site_5_0 -x 230 -y 30 -width 48 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tBu46 \
        -in $site_5_0 -x 280 -y 30 -width 38 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu47 \
        -in $site_5_0 -x 250 -y 2 -width 68 -height 26 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_4_0.tFr40
    place $site_4_0.scr43 \
        -in $site_4_0 -x 2 -y 80 -width 334 -relwidth 0 -height 603 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tFr40 \
        -in $site_4_0 -x 0 -y 20 -width 335 -relwidth 0 -height 63 \
        -relheight 0 -anchor nw -bordermode ignore 
    $top.tPa40 add $top.tPa40.p1 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa40.p2 \
        -text Workspace -width 455 -height 460 
    vTcl:DefineAlias "$top.tPa40.p2" "EditPane" vTcl:WidgetProc "TraitGUI" 1
    set site_4_1 $top.tPa40.p2
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_1.scr40 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_1.scr40" "Viewer" vTcl:WidgetProc "TraitGUI" 1

    $site_4_1.scr40.01 configure -background white \
        -font font9 \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl:copy_lock $site_4_1.scr40
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $site_4_1.tFr48 \
        -borderwidth 2 -relief groove -width 455 -height 45 
    vTcl:DefineAlias "$site_4_1.tFr48" "EditButtonFrame" vTcl:WidgetProc "TraitGUI" 1
    set site_5_0 $site_4_1.tFr48
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu49 \
        -command ValidEdit -takefocus {} -text Validate 
    vTcl:DefineAlias "$site_5_0.tBu49" "ValidEdit" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu50 \
        -command SaveEdit -takefocus {} -text Save 
    vTcl:DefineAlias "$site_5_0.tBu50" "SaveEdit" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu51 \
        -command ReloadEdit -takefocus {} -text Reload 
    vTcl:DefineAlias "$site_5_0.tBu51" "ReloadEdit" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu52 \
        -command ClearEdit -takefocus {} -text Clear 
    vTcl:DefineAlias "$site_5_0.tBu52" "ClearEdit" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu53 \
        -command ExportEdit -takefocus {} -text Export 
    vTcl:DefineAlias "$site_5_0.tBu53" "ExportEdit" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu54 \
        -command ImportEdit -takefocus {} -text Import 
    vTcl:DefineAlias "$site_5_0.tBu54" "ImportEdit" vTcl:WidgetProc "TraitGUI" 1
    place $site_5_0.tBu49 \
        -in $site_5_0 -x 10 -y 10 -width 58 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu50 \
        -in $site_5_0 -x 70 -y 10 -width 68 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu51 \
        -in $site_5_0 -x 140 -y 10 -width 78 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu52 \
        -in $site_5_0 -x 220 -y 10 -width 78 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu53 \
        -in $site_5_0 -x 300 -y 10 -width 68 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu54 \
        -in $site_5_0 -x 370 -y 10 -width 78 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.scr40 \
        -in $site_4_1 -x 0 -y 80 -width 455 -relwidth 0 -height 603 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tFr48 \
        -in $site_4_1 -x 0 -y 20 -width 455 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    $top.tPa40 add $top.tPa40.p2 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa40.p3 \
        -text Triggers -width 626.0 
    vTcl:DefineAlias "$top.tPa40.p3" "TriggerPane" vTcl:WidgetProc "TraitGUI" 1
    set site_4_2 $top.tPa40.p3
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_2.scr49 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_2.scr49" "TriggerListt" vTcl:WidgetProc "TraitGUI" 1

    $site_4_2.scr49.01 configure -background white \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -listvariable TriggerList
    vTcl:copy_lock $site_4_2.scr49
    place $site_4_2.scr49 \
        -in $site_4_2 -x 0 -y 80 -width 345 -relwidth 0 -height 603 \
        -relheight 0 -anchor nw -bordermode ignore 
    $top.tPa40 add $top.tPa40.p3 
        
    set site_3_0 $top.m41
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font font9 -foreground {#000000} -tearoff 0 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#OpenFile} \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label Open 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#ReloadFile} \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label Reload 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#SaveFile} \
        -font {-family {DejaVu Sans} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label Save 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#SaveFileAs} \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label {Save as} 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#FilterWin} \
        -font {-family {DejaVu Sans} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label Filters 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#ValidateFile} \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label Validate 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#Quit} \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {#000000} -label Quit 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPa40 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

