#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 08, 2018 10:38:52 PM JST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m41" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1148x688+504+162
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1030
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "EDCT Explore"
    vTcl:DefineAlias "$top" "TraitGUI" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TPanedwindow -background #d9d9d9
    ttk::style configure TPanedwindow.Label -background #d9d9d9
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font TkDefaultFont
    ttk::panedwindow $top.tPa40 \
        -orient horizontal 
    vTcl:DefineAlias "$top.tPa40" "PaneWin" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa40.p1 \
        -text Traits -width 338 -height 460 
    vTcl:DefineAlias "$top.tPa40.p1" "TraitPane" vTcl:WidgetProc "TraitGUI" 1
    set site_4_0 $top.tPa40.p1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_0.scr43 \
        -background {#d9d9d9} -height 603 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 334 
    vTcl:DefineAlias "$site_4_0.scr43" "TraitListt" vTcl:WidgetProc "TraitGUI" 1

    $site_4_0.scr43.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -listvariable TraitList
    vTcl:copy_lock $site_4_0.scr43
    ttk::entry $site_4_0.tEn45 \
        -textvariable traitsearched -foreground {} -background {} \
        -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_0.tEn45" "TriggerEntry" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_0.tBu46 \
        -command GoToTrait -takefocus {} -text Go 
    vTcl:DefineAlias "$site_4_0.tBu46" "GoToTrait" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_0.tBu48 \
        -command ViewTrait -takefocus {} -text View 
    vTcl:DefineAlias "$site_4_0.tBu48" "ViewTrait" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_0.tBu40 \
        -command FilterTrait -takefocus {} -text Filter 
    vTcl:DefineAlias "$site_4_0.tBu40" "FilterTrait" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_0.tBu41 \
        -command QueryTrait -takefocus {} -text Query 
    vTcl:DefineAlias "$site_4_0.tBu41" "QueryTrait" vTcl:WidgetProc "TraitGUI" 1
    place $site_4_0.scr43 \
        -in $site_4_0 -x 2 -y 80 -width 334 -relwidth 0 -height 603 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tEn45 \
        -in $site_4_0 -x 10 -y 40 -width 186 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu46 \
        -in $site_4_0 -x 200 -y 40 -width 48 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu48 \
        -in $site_4_0 -x 250 -y 40 -width 48 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu40 \
        -in $site_4_0 -x 250 -y 10 -width 48 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu41 \
        -in $site_4_0 -x 200 -y 10 -width 48 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    $top.tPa40 add $top.tPa40.p1 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa40.p2 \
        -text View/Edit -width 455 -height 460 
    vTcl:DefineAlias "$top.tPa40.p2" "EditPane" vTcl:WidgetProc "TraitGUI" 1
    set site_4_1 $top.tPa40.p2
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_1.tBu53 \
        -command SaveEdit -takefocus {} -text Save 
    vTcl:DefineAlias "$site_4_1.tBu53" "SaveEdit" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_1.tBu55 \
        -command ValidEdit -takefocus {} -text Validate 
    vTcl:DefineAlias "$site_4_1.tBu55" "ValidEdit" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_1.tBu42 \
        -command ReloadEdit -takefocus {} -text Reload 
    vTcl:DefineAlias "$site_4_1.tBu42" "ReloadEdit" vTcl:WidgetProc "TraitGUI" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_1.scr40 \
        -background {#d9d9d9} -height 604 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 455 
    vTcl:DefineAlias "$site_4_1.scr40" "Viewer" vTcl:WidgetProc "TraitGUI" 1

    $site_4_1.scr40.01 configure -background white \
        -font font9 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl:copy_lock $site_4_1.scr40
    place $site_4_1.tBu53 \
        -in $site_4_1 -x 10 -y 30 -width 68 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tBu55 \
        -in $site_4_1 -x 90 -y 30 -width 78 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tBu42 \
        -in $site_4_1 -x 180 -y 30 -width 78 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_1.scr40 \
        -in $site_4_1 -x 0 -y 80 -width 455 -relwidth 0 -height 603 \
        -relheight 0 -anchor nw -bordermode ignore 
    $top.tPa40 add $top.tPa40.p2 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa40.p3 \
        -text Trigger -width 626.0 
    vTcl:DefineAlias "$top.tPa40.p3" "TriggerPane" vTcl:WidgetProc "TraitGUI" 1
    set site_4_2 $top.tPa40.p3
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_2.scr49 \
        -background {#d9d9d9} -height 603 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 345 
    vTcl:DefineAlias "$site_4_2.scr49" "TriggerListt" vTcl:WidgetProc "TraitGUI" 1

    $site_4_2.scr49.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -listvariable TriggerList
    vTcl:copy_lock $site_4_2.scr49
    ttk::entry $site_4_2.tEn50 \
        -textvariable triggersearched -foreground {} -background {} \
        -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_2.tEn50" "TEntry2" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_2.tBu51 \
        -takefocus {} -text Tbutton 
    vTcl:DefineAlias "$site_4_2.tBu51" "TButton2" vTcl:WidgetProc "TraitGUI" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_2.tBu52 \
        -takefocus {} -text Tbutton 
    vTcl:DefineAlias "$site_4_2.tBu52" "TButton3" vTcl:WidgetProc "TraitGUI" 1
    place $site_4_2.scr49 \
        -in $site_4_2 -x 0 -y 80 -width 345 -relwidth 0 -height 603 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tEn50 \
        -in $site_4_2 -x 10 -y 40 -width 186 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu51 \
        -in $site_4_2 -x 220 -y 40 -width 38 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu52 \
        -in $site_4_2 -x 270 -y 40 -width 38 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    $top.tPa40 add $top.tPa40.p3 
        
    set site_3_0 $top.m41
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font font9 -foreground {#000000} -tearoff 0 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#OpenFile} \
        -font [vTcl:font:getFontFromDescr "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Open 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#ReloadFile} \
        -font [vTcl:font:getFontFromDescr "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Reload 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#SaveAs} \
        -font [vTcl:font:getFontFromDescr "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Save as} 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#Valid} \
        -font [vTcl:font:getFontFromDescr "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Validate 
    $site_3_0 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#Quit} \
        -font [vTcl:font:getFontFromDescr "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Quit 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPa40 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

